QLLDGV/QLLDGV/Controllers/SuKienGVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Database.Framework;
using PagedList;

namespace QLLDGV.Controllers
{
    public class SuKienGVController : BaseGVController
    {
        private UserDbContext db = new UserDbContext();

        // GET: SuKienGV
        public ActionResult Index(int? page, string SearchString, string currentFilter)
        {
            var session = (UserLogin)Session[QLLDGV.Common.CommonConstants.USER_SESSION];
            var links = new List<SuKien>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                links = db.SuKiens.Where(n => n.GiaoVien == session.UserID &&
                                            n.TenSuKien.Contains(SearchString) ||
                                            n.MonHoc.TenMH.Contains(SearchString) ||
                                            n.HocPhan.TenKhoa.Contains(SearchString)).ToList();
            }
            else
            {
                links = db.SuKiens.Where(n => n.GiaoVien == session.UserID).ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            links = links.OrderByDescending(n => n.StartDate).ToList();
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        // GET: SuKienGV/Create
        public ActionResult Create()
        {
            ViewBag.Nhom = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            ViewBag.TenHP = new SelectList(db.MonHocs, "MaMH", "TenMH");
            return View();
        }
        public JsonResult GetNhomHPList(string MaHP)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Khoa> NhomHPList = db.Khoas.Where(x => x.MonHoc == MaHP).ToList();
            return Json(NhomHPList, JsonRequestBehavior.AllowGet);
        }

        // POST: SuKienGV/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSuKien,TenHP,Nhom,GiaoVien,TenSuKien,StartDate")] SuKien suKien)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[QLLDGV.Common.CommonConstants.USER_SESSION];
                suKien.MaSuKien = Guid.NewGuid();
                suKien.GiaoVien = session.UserID;
                db.SuKiens.Add(suKien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GiaoVien = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", suKien.GiaoVien);
            ViewBag.Nhom = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", suKien.Nhom);
            ViewBag.TenHP = new SelectList(db.MonHocs, "MaMH", "TenMH", suKien.TenHP);
            return View(suKien);
        }

        // GET: SuKienGV/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuKien suKien = db.SuKiens.Find(id);
            if (suKien == null)
            {
                return HttpNotFound();
            }
            ViewBag.GiaoVien = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", suKien.GiaoVien);
            ViewBag.Nhom = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", suKien.Nhom);
            ViewBag.TenHP = new SelectList(db.MonHocs, "MaMH", "TenMH", suKien.TenHP);
            return View(suKien);
        }

        // POST: SuKienGV/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSuKien,TenHP,Nhom,GiaoVien,TenSuKien,StartDate")] SuKien suKien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(suKien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GiaoVien = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", suKien.GiaoVien);
            ViewBag.Nhom = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", suKien.Nhom);
            ViewBag.TenHP = new SelectList(db.MonHocs, "MaMH", "TenMH", suKien.TenHP);
            return View(suKien);
        }

        // GET: SuKienGV/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuKien suKien = db.SuKiens.Find(id);
            if (suKien == null)
            {
                return HttpNotFound();
            }
            return View(suKien);
        }

        // POST: SuKienGV/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            SuKien suKien = db.SuKiens.Find(id);
            db.SuKiens.Remove(suKien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLLDGV/QLLDGV/Views/SuKienGV/Create.cshtml
@model Database.Framework.SuKien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SuKien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenHP, "Tên môn học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.TenHP != null)
                {
                    @Html.DropDownListFor(model => model.TenHP, ViewBag.HOCPHANList as SelectList, "-- Môn học --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nhom, "Tên nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Nhom, new SelectList(" "), "-- Nhóm --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nhom, "", new { @class = "text-danger" })
            </div>
        </div>

        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script>
                $(document).ready(function () {
                    $("#TenHP").change(function () {
                        $.get("/SuKienGV/GetNhomHPList", { MaHP: $("#TenHP").val() }, function (data) {
                            $("#Nhom").empty();
                            $.each(data, function(index, row) {
                                $("#Nhom").append("<option value='"+row.MaNhom+"'>"+row.TenNhom+"</option>")
                            });
                        });
                    })
                });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSuKien, "Tên sự kiện",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Ngày thực hiện",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLLDGV/QLLDGV/Views/SuKienGV/Delete.cshtml
@model Database.Framework.SuKien

@{
    ViewBag.Title = "Xóa sự kiện";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3>Xóa sự kiện này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sự kiện
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSuKien)
        </dd>

        <dt>
            Giảng viên
        </dt>

        <dt>
            Tên môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMH)
        </dd>

        <dt>
            Nhóm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HocPhan.TenKhoa)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.GIAOVIEN1.HoTenGV)
        </dd>


        <dt>
            Ngày thực hiện
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLLDGV/QLLDGV/Views/SuKienGV/Edit.cshtml
@model Database.Framework.SuKien

@{
    ViewBag.Title = "Thay đổi thông tin sự kiện";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Thay đổi thông tin sự kiện</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSuKien)

        <div class="form-group">
            @Html.LabelFor(model => model.TenHP, "Tên môn học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TenHP)
                @Html.DropDownList("TenHP", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nhom, "Nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Nhom)
                @Html.DropDownList("Nhom", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.Nhom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaoVien, "Giảng viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.GiaoVien)
                @Html.DropDownList("GiaoVien", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.GiaoVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSuKien, "Tên sự kiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Ngày thực hiện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLLDGV/QLLDGV/Views/SuKienGV/Index.cshtml
@model PagedList.IPagedList<Database.Framework.SuKien>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Sự kiện";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Danh sách sự kiện</h2>
<link href="~/Content/PagedList.css" rel="stylesheet" />
<p>
    @Html.ActionLink("Thêm sự kiện", "Create") |
    <a href="/CalendarGV/SuKien">Xem dưới định dạng lịch</a>
</p>
<div>
    @using (Html.BeginForm("Index", "SuKienGV", FormMethod.Get))
    {
        <table class="table1" align="center" style="margin-bottom: 20px">
            <tr>
                <td>
                    <div>Tìm kiếm</div>
                </td>
                <td>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                </td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" class="btn btn-primary" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" class="btn btn-success" onclick="location.href='@Url.Action("Index", "SuKienGV/Create")'" />
                </td>
            </tr>
        </table>
    }
</div>
<table class="table">
    <tr>
        <th>
            Tên sự kiện
        </th>
        <th>
            Tên môn học
        </th>
        <th>
            Tên nhóm
        </th>
        <th>
            Ngày thực hiện
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSuKien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonHoc.TenMH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HocPhan.TenKhoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaSuKien }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaSuKien })
            </td>
        </tr>
    }

</table>
<div class="page-count" style="display: inline-block; vertical-align:middle;">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) trên @Model.PageCount
</div>
<br />
<div class="pagination" style="display: inline-block; vertical-align: middle;">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
</div>