QLLDGV/QLLDGV/Models/LichDay.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLDGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDay
    {
        public System.Guid MaLich { get; set; }
        public string TenMH { get; set; }
        public System.Guid NhomHP { get; set; }
        public string PhongHoc { get; set; }
        public Nullable<System.Guid> GVDay { get; set; }
        public string ThuNgay { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GioBatDau { get; set; }
        public string GioKetThuc { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual TietHoc TietHoc { get; set; }
        public virtual TietHoc TietHoc1 { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual THU THU { get; set; }
    }
}

QLLDGV/QLLDGV/Areas/Admin/Controllers/LichDaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Database.Framework;
using PagedList;

namespace QLLDGV.Areas.Admin.Controllers
{
    public class LichDaysController : BaseController
    {
        private UserDbContext db = new UserDbContext();

        // GET: Admin/LichDays
        public ActionResult Index(int? page, string SearchString, string currentFilter)
        {
            var links = new List<LichDay>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                links = db.LichDays.Where(n => n.GIAOVIEN.HoTenGV.Contains(SearchString) ||
                                            n.MonHoc.TenMH.Contains(SearchString) ||
                                            n.HocPhan.TenKhoa.Contains(SearchString) ||
                                            n.THU.TenThu.Contains(SearchString) ||
                                            n.PHONG.TenPhong.Contains(SearchString)).ToList();
            }
            else
            {
                links = db.LichDays.Include(l => l.GIAOVIEN).Include(l => l.MonHoc).Include(l => l.TietHoc).Include(l => l.TietHoc1).Include(l => l.PHONG).Include(l => l.THU).ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            links = links.OrderByDescending(n => n.MonHoc.TenMH).ToList();
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/LichDays/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichDay lichDay = db.LichDays.Find(id);
            if (lichDay == null)
            {
                return HttpNotFound();
            }
            return View(lichDay);
        }

        // GET: Admin/LichDays/Create
        public ActionResult Create()
        {
            ViewBag.GVDay = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV");
            ViewBag.NhomHP = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            ViewBag.TenMH = new SelectList(db.MonHocs, "MaMH", "TenMH");
            ViewBag.PhongHoc = new SelectList(db.PHONGs, "MaPhong", "TenPhong");
            ViewBag.ThuNgay = new SelectList(db.THUs, "MaThu", "TenThu");
            ViewBag.GioBatDau = new SelectList(db.TietHocs, "MaTiet", "Tiet");
            ViewBag.GioKetThuc = new SelectList(db.TietHocs, "MaTiet", "Tiet");
            return View();
        }
        public JsonResult GetNhomHPList(string MaMH)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Khoa> NhomHPList = db.Khoas.Where(x => x.MonHoc1.MaMH == MaMH).ToList();
            return Json(NhomHPList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetGVList(string MaMH)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<GIAOVIEN> GiaoVienList = db.GIAOVIENs.Where(x => x.BoMonPhuTrach == MaMH).ToList();
            return Json(GiaoVienList, JsonRequestBehavior.AllowGet);
        }

        // POST: Admin/LichDays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLich,TenMH,PhongHoc,GVDay,ThuNgay,NgayBatDau,NgayKetThuc,GioBatDau,GioKetThuc")] LichDay lichDay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lichDay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GVDay = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", lichDay.GVDay);
            ViewBag.NhomHP = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", lichDay.NhomHP);
            ViewBag.TenMH = new SelectList(db.MonHocs, "MaMH", "TenMH", lichDay.TenMH);
            ViewBag.PhongHoc = new SelectList(db.PHONGs, "MaPhong", "TenPhong", lichDay.PhongHoc);
            ViewBag.ThuNgay = new SelectList(db.THUs, "MaThu", "TenThu", lichDay.ThuNgay);
            ViewBag.GioBatDau = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioBatDau);
            ViewBag.GioKetThuc = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioKetThuc);
            return View(lichDay);
        }

        // GET: Admin/LichDays/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichDay lichDay = db.LichDays.Find(id);
            if (lichDay == null)
            {
                return HttpNotFound();
            }
            ViewBag.GVDay = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", lichDay.GVDay);
            ViewBag.NhomHP = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", lichDay.NhomHP);
            ViewBag.TenMH = new SelectList(db.MonHocs, "MaMH", "TenMH", lichDay.TenMH);
            ViewBag.PhongHoc = new SelectList(db.PHONGs, "MaPhong", "TenPhong", lichDay.PhongHoc);
            ViewBag.ThuNgay = new SelectList(db.THUs, "MaThu", "TenThu", lichDay.ThuNgay);
            ViewBag.GioBatDau = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioBatDau);
            ViewBag.GioKetThuc = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioKetThuc);
            return View(lichDay);
        }

        // POST: Admin/LichDays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLich,TenMH,PhongHoc,GVDay,ThuNgay,NgayBatDau,NgayKetThuc,GioBatDau,GioKetThuc")] LichDay lichDay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lichDay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GVDay = new SelectList(db.GIAOVIENs, "MaGV", "HoTenGV", lichDay.GVDay);
            ViewBag.NhomHP = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", lichDay.NhomHP);
            ViewBag.TenMH = new SelectList(db.MonHocs, "MaMH", "TenMH", lichDay.TenMH);
            ViewBag.PhongHoc = new SelectList(db.PHONGs, "MaPhong", "TenPhong", lichDay.PhongHoc);
            ViewBag.ThuNgay = new SelectList(db.THUs, "MaThu", "TenThu", lichDay.ThuNgay);
            ViewBag.GioBatDau = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioBatDau);
            ViewBag.GioKetThuc = new SelectList(db.TietHocs, "MaTiet", "Tiet", lichDay.GioKetThuc);
            return View(lichDay);
        }

        // GET: Admin/LichDays/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichDay lichDay = db.LichDays.Find(id);
            if (lichDay == null)
            {
                return HttpNotFound();
            }
            return View(lichDay);
        }

        // POST: Admin/LichDays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            LichDay lichDay = db.LichDays.Find(id);
            db.LichDays.Remove(lichDay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLLDGV/QLLDGV/Areas/Admin/Views/LichDays/Create.cshtml
@model Database.Framework.LichDay

@{
    ViewBag.Title = "Thêm lịch dạy";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm lịch dạy</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenMH, "Tên môn học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TenMH", null, "-- Môn học --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.NhomHP, "Nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NhomHP", new SelectList(" "), "-- Nhóm học phần --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NhomHP, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
            <script>
                $(document).ready(function () {
                    $("#TenMH").change(function () {
                        $.get("/LichDays/GetNhomHPList", { MaMH: $("#TenMH").val() }, function (data) {
                            $("#NhomHP").empty();
                            $.each(data, function(index, row) {
                                $("#NhomHP").append("<option value='"+row.MaNhom+"'>"+row.TenNhom+"</option>")
                            });
                        });
                    })
                });
            </script>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PhongHoc, "Phòng học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PhongHoc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PhongHoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GVDay, "Giảng viên dạy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GVDay", new SelectList(" "), "-- Giảng viên --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GVDay, "", new { @class = "text-danger" })
            </div>
        </div>
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
            <script>
                $(document).ready(function () {
                    $("#TenMH").change(function () {
                        $.get("/LichDays/GetGVList", { MaMH: $("#TenMH").val() }, function (data) {
                            $("#GVDay").empty();
                            $.each(data, function(index, row) {
                                $("#GVDay").append("<option value='"+row.MaGV+"'>"+row.HoTenGV+"</option>")
                            });
                        });
                    })
                });
            </script>

        <div class="form-group">
            @Html.LabelFor(model => model.ThuNgay, "Thứ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ThuNgay", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThuNgay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayBatDau, "Ngày bắt đầu",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayKetThuc, "Ngày kết thúc",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioBatDau, "Tiết bắt đầu học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioBatDau", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioBatDau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioKetThuc, "Tiết kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioKetThuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLLDGV/QLLDGV/Areas/Admin/Views/LichDays/Delete.cshtml
@model Database.Framework.LichDay

@{
    ViewBag.Title = "Xóa lịch dạy";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h3>Xóa lịch dạy này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMH)
        </dd>

        @*<dt>
            Nhóm
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.HocPhan.TenKhoa)
        </dd>

        <dt>
            Giảng viên dạy
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIAOVIEN.HoTenGV)
        </dd>

        <dt>
            Thời gian dạy
        </dt>

        <dd>
            Từ:  @Html.DisplayFor(model => model.NgayBatDau)  -  Đến:  @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>

        <dt>
            Vào ngày thứ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.THU.TenThu)
        </dd>

        <dt>
            Tiết học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TietHoc.Tiet) - @Html.DisplayFor(model => model.TietHoc1.Tiet)
        </dd>

        <dt>
            Giờ học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TietHoc.TGianBD) - @Html.DisplayFor(model => model.TietHoc1.TGianKT)
        </dd>

        <dt>
            Phòng học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHONG.TenPhong)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLLDGV/QLLDGV/Areas/Admin/Views/LichDays/Details.cshtml
@model Database.Framework.LichDay

@{
    ViewBag.Title = "Thông tin lịch dạy";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thông tin lịch dạy</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMH)
        </dd>

        @*<dt>
            Nhóm
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.HocPhan.TenKhoa)
        </dd>

        <dt>
            Giảng viên dạy
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIAOVIEN.HoTenGV)
        </dd>

        <dt>
            Thời gian dạy
        </dt>

        <dd>
            Từ:  @Html.DisplayFor(model => model.NgayBatDau)  -  Đến:  @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>

        <dt>
            Vào ngày thứ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.THU.TenThu)
        </dd>

        <dt>
            Tiết học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TietHoc.Tiet) - @Html.DisplayFor(model => model.TietHoc1.Tiet)
        </dd>

        <dt>
            Giờ học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TietHoc.TGianBD) - @Html.DisplayFor(model => model.TietHoc1.TGianKT)
        </dd>

        <dt>
            Phòng học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHONG.TenPhong)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaLich }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

QLLDGV/QLLDGV/Areas/Admin/Views/LichDays/Edit.cshtml
@model Database.Framework.LichDay

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LichDay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaLich)

        <div class="form-group">
            @Html.LabelFor(model => model.TenMH, "Tên môn học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TenMH)
                @Html.DropDownList("TenMH", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.NhomHP, "Nhóm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.NhomHP)
                @Html.DropDownList("NhomHP", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.NhomHP, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PhongHoc, "Phòng học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PhongHoc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PhongHoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GVDay, "Giảng viên dạy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.GVDay)
                @Html.DropDownList("GVDay", null, htmlAttributes: new { @class = "form-control", @disabled = "" })
                @Html.ValidationMessageFor(model => model.GVDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThuNgay, "Thứ ngày", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ThuNgay", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThuNgay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayBatDau, "Ngày bắt đầu học",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayKetThuc, "Ngày kết thúc",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioBatDau, "Tiết bắt đầu học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioBatDau", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioBatDau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioKetThuc, "Tiết kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioKetThuc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLLDGV/QLLDGV/Areas/Admin/Views/LichDays/Index.cshtml
@model PagedList.IPagedList<Database.Framework.LichDay>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách lịch dạy";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách lịch dạy</h2>
<link href="~/Content/PagedList.css" rel="stylesheet" />
<p>
    <a href="/Admin/Calendar/Calendar" style="text-decoration: none; color: #007bff; font-weight: bold; transition: color 0.3s ease;">Xem dưới định dạng lịch</a>
</p>
<div>
    @using (Html.BeginForm("Index", "LichDays", FormMethod.Get))
    {
        <table class="table1" align="center" style="margin-bottom: 20px">
            <tr>
                <td>
                    <div>Tìm kiếm</div>
                </td>
                <td>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                </td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" class="btn btn-primary" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" class="btn btn-success" onclick="location.href='@Url.Action("Index", "LichDays/Create")'" />
                </td>
            </tr>
        </table>
    }
</div>
<table class="table">
    <tr>
        <th>
            Tên môn học
        </th>
        @*<th>
            Nhóm
        </th>*@
        <th>
            Giảng viên dạy
        </th>
        <th>
            Thứ
        </th>
        <th>
            Tiết học
        </th>
        <th>
            Thời gian học
        </th>
        <th>
            Phòng học
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MonHoc.TenMH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HocPhan.TenKhoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GIAOVIEN.HoTenGV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.THU.TenThu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TietHoc.Tiet) - @Html.DisplayFor(modelItem => item.TietHoc1.Tiet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TietHoc.TGianBD) - @Html.DisplayFor(modelItem => item.TietHoc1.TGianKT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PHONG.TenPhong)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaLich }) |
                @Html.ActionLink("Xem", "Details", new { id = item.MaLich }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaLich })
            </td>
        </tr>
    }

</table>
<div class="page-count" style="display: inline-block; vertical-align:middle;">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) trên @Model.PageCount
</div>
<br />
<div class="pagination" style="display: inline-block; vertical-align: middle;">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
</div>