QLLDGV/QLLDGV/Models/GIAOVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLDGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN()
        {
            this.LichDays = new HashSet<LichDay>();
            this.Messages = new HashSet<Message>();
            this.SuKiens = new HashSet<SuKien>();
        }
    
        public System.Guid MaGV { get; set; }
        public string HoTenGV { get; set; }
        public string BoMonPhuTrach { get; set; }
        public string SodtGV { get; set; }
        public string EmailGV { get; set; }
        public string QueQuan { get; set; }
        public string MatKhauGV { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichDay> LichDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKien> SuKiens { get; set; }
    }
}

QLLDGV/QLLDGV/Areas/Admin/Controllers/GIAOVIENsController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Database.Framework;
using PagedList.Mvc;
using PagedList;
using System.Web.UI;

namespace QLLDGV.Areas.Admin.Controllers
{
    public class GIAOVIENsController : BaseController
    {
        private UserDbContext db = new UserDbContext();

        // GET: Admin/GIAOVIENs
        public ActionResult Index(int? page, string SearchString, string currentFilter)
        {
            var links = new List<GIAOVIEN>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                links = db.GIAOVIENs.Where(n => n.HoTenGV.Contains(SearchString) ||
                                            n.MonHoc.TenMH.Contains(SearchString)).ToList();
            }
            else
            {
                links = db.GIAOVIENs.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            links = links.OrderByDescending(n => n.BoMonPhuTrach).ToList();
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/GIAOVIENs/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            if (gIAOVIEN == null)
            {
                return HttpNotFound();
            }
            return View(gIAOVIEN);
        }

        // GET: Admin/GIAOVIENs/Create
        public ActionResult Create()
        {
            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH");
            return View();
        }
        public JsonResult CheckEmailGV(string emailGV)
        {
            System.Threading.Thread.Sleep(200);
            var SearchData = db.GIAOVIENs.Where(x => x.EmailGV == emailGV).SingleOrDefault();
            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        // POST: Admin/GIAOVIENs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGV,HoTenGV,BoMonPhuTrach,SodtGV,EmailGV,QueQuan,MatKhauGV")] GIAOVIEN gIAOVIEN)
        {
            if (ModelState.IsValid)
            {
                gIAOVIEN.MaGV = Guid.NewGuid();
                db.GIAOVIENs.Add(gIAOVIEN);
                db.SaveChanges();
                ViewBag.SuccessMessage = "Thêm giáo viên thành công!";
                return RedirectToAction("Index");
            }

            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH", gIAOVIEN.BoMonPhuTrach);
            return View(gIAOVIEN);
        }

        // GET: Admin/GIAOVIENs/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            if (gIAOVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH", gIAOVIEN.BoMonPhuTrach);
            return View(gIAOVIEN);
        }

        // POST: Admin/GIAOVIENs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGV,HoTenGV,BoMonPhuTrach,SodtGV,EmailGV,QueQuan,MatKhauGV")] GIAOVIEN gIAOVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gIAOVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH", gIAOVIEN.BoMonPhuTrach);
            return View(gIAOVIEN);
        }

        // GET: Admin/GIAOVIENs/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            if (gIAOVIEN == null)
            {
                return HttpNotFound();
            }
            return View(gIAOVIEN);
        }

        // POST: Admin/GIAOVIENs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            db.GIAOVIENs.Remove(gIAOVIEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLLDGV/QLLDGV/Controllers/GIAOVIENController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Database.Framework;

namespace QLLDGV.Controllers
{
    public class GIAOVIENController : BaseGVController
    {
        private UserDbContext db = new UserDbContext();

        // GET: GIAOVIEN
        public ActionResult Index(Guid? id)
        {
            var session = (UserLogin)Session[QLLDGV.Common.CommonConstants.USER_SESSION];
            id = session.UserID;
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            if (gIAOVIEN == null)
            {
                return HttpNotFound();
            }
            return View(gIAOVIEN);
        }

        // GET: GIAOVIEN/Edit/5
        public ActionResult Edit(Guid? id)
        {
            var session = (UserLogin)Session[QLLDGV.Common.CommonConstants.USER_SESSION];
            id = session.UserID;
            GIAOVIEN gIAOVIEN = db.GIAOVIENs.Find(id);
            if (gIAOVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH", gIAOVIEN.BoMonPhuTrach);
            return View(gIAOVIEN);
        }

        // POST: GIAOVIEN/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGV,HoTenGV,BoMonPhuTrach,SodtGV,EmailGV,QueQuan,MatKhauGV")] GIAOVIEN gIAOVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gIAOVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BoMonPhuTrach = new SelectList(db.MonHocs, "MaMH", "TenMH", gIAOVIEN.BoMonPhuTrach);
            return View(gIAOVIEN);
        }
    }
}

QLLDGV/QLLDGV/Areas/Admin/Views/GIAOVIENs/Create.cshtml
@model Database.Framework.GIAOVIEN

@{
    ViewBag.Title = "Thêm giáo viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm giáo viên</h2>

@if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
{
    <div class="alert alert-success">@ViewBag.SuccessMessage</div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.HoTenGV, "Tên giảng viên*", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTenGV, new { htmlAttributes = new { @class = "form-control" } })
            @if (!ViewData.ModelState.IsValidField("HoTenGV"))
            {
                <span class="text-danger">Không được bỏ trống</span>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BoMonPhuTrach, "Bộ môn phụ trách*", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BoMonPhuTrach", null, htmlAttributes: new { @class = "form-control" })
            @if (!ViewData.ModelState.IsValidField("BoMonPhuTrach"))
            {
                <span class="text-danger">Không được bỏ trống</span>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SodtGV, "Số điện thoại*", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SodtGV, new { htmlAttributes = new { @class = "form-control" } })
            @if (!ViewData.ModelState.IsValidField("SodtGV"))
            {
                <span class="text-danger">Không được bỏ trống</span>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailGV, "Email*", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailGV, new { htmlAttributes = new { @class = "form-control" } })
            @if (!ViewData.ModelState.IsValidField("EmailGV"))
            {
                <span class="text-danger">Không được bỏ trống</span>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QueQuan, "Quê quán", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhauGV, "Mật khẩu*", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhauGV, new { htmlAttributes = new { @class = "form-control" } })
            @if (!ViewData.ModelState.IsValidField("MatKhauGV"))
            {
                <span class="text-danger">Không được bỏ trống</span>
            }
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

<script>
    function EmailCheck() {
        $("#Status").html("Đang kiểm tra...");
        $.post("@Url.Action("CheckEmailGV", "GIAOVIENs")",
            {
                emailGV: $("#EmailGV").val()
            },
            function (data) {
                if (data == 0) {
                    $("#Status").html('<font color="Green"></font>');
                    $("#EmailGV").css("border-color", "Green");
                }
                else {
                    $("#Status").html('<font color="Red">Email đã được sử dụng</font>');
                    $("#EmailGV").css("border-color", "Red");
                }
            });
    }
</script>

QLLDGV/QLLDGV/Areas/Admin/Views/GIAOVIENs/Delete.cshtml
@model Database.Framework.GIAOVIEN

@{
    ViewBag.Title = "Xóa giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Xóa giảng viên này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên giảng viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTenGV)
        </dd>

        <dt>
            Bộ môn phụ trách
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMH)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SodtGV)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailGV)
        </dd>

        <dt>
            Quê quán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLLDGV/QLLDGV/Areas/Admin/Views/GIAOVIENs/Details.cshtml
@model Database.Framework.GIAOVIEN

@{
    ViewBag.Title = "Thông tin giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thông tin giảng viên</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên giảng viên 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTenGV)
        </dd>

        <dt>
            Bộ môn phụ trách
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMH)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SodtGV)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailGV)
        </dd>

        <dt>
            Quê quán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaGV }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

QLLDGV/QLLDGV/Areas/Admin/Views/GIAOVIENs/Edit.cshtml
@model Database.Framework.GIAOVIEN

@{
    ViewBag.Title = "Thay đổi thông tin giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thay đổi thông tin giáo viên</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaGV)

        <div class="form-group">
            @Html.LabelFor(model => model.HoTenGV, "Tên giảng viên*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTenGV, new { htmlAttributes = new { @class = "form-control" } })
                @if (!ViewData.ModelState.IsValidField("HoTenGV"))
                {
                    <span class="text-danger">Không được bỏ trống</span>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BoMonPhuTrach, "Bộ môn phụ trách*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BoMonPhuTrach", null, htmlAttributes: new { @class = "form-control" })
                @if (!ViewData.ModelState.IsValidField("BoMonPhuTrach"))
                {
                    <span class="text-danger">Không được bỏ trống</span>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SodtGV, "Số điện thoại*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SodtGV, new { htmlAttributes = new { @class = "form-control" } })
                @if (!ViewData.ModelState.IsValidField("SodtGV"))
                {
                    <span class="text-danger">Không được bỏ trống</span>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailGV, "Email*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailGV, new { htmlAttributes = new { @class = "form-control" } })
                @if (!ViewData.ModelState.IsValidField("EmailGV"))
                {
                    <span class="text-danger">Không được bỏ trống</span>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueQuan, "Quê quán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhauGV, "Mật khẩu*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhauGV, new { htmlAttributes = new { @class = "form-control" } })
                @if (!ViewData.ModelState.IsValidField("MatKhauGV"))
                {
                    <span class="text-danger">Không được bỏ trống</span>
                }
            </div>
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

QLLDGV/QLLDGV/Areas/Admin/Views/GIAOVIENs/Index.cshtml
@model PagedList.IPagedList<Database.Framework.GIAOVIEN>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách giáo viên</h2>
<link href="~/Content/PagedList.css" rel="stylesheet" />
<div>
    @using (Html.BeginForm("Index", "GIAOVIENs", FormMethod.Get))
    {
        <table class="table1" align="center" style="margin-bottom: 20px">
            <tr>
                <td>
                    <div>Tìm kiếm</div>
                </td>
                <td>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                </td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" class="btn btn-primary" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" class="btn btn-success" onclick="location.href='@Url.Action("Index", "GIAOVIENs/Create")'"  />
                </td>

            </tr>
        </table>
    }
</div>
<table class="table">
    <tr>
        <th>
            Tên giảng viên
        </th>
        <th>
            Bộ môn phụ trách
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTenGV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonHoc.TenMH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailGV)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaGV }) |
                @Html.ActionLink("Xem", "Details", new { id = item.MaGV }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaGV })
            </td>
        </tr>
    }

</table>
<div class="page-count" style="display: inline-block; vertical-align:middle;">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) trên @Model.PageCount
</div>
<br />
<div class="pagination" style="display: inline-block; vertical-align: middle;">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
</div>